version: '3.6'
services:
  
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  graphql-engine:
    image: hasura/graphql-engine:v2.0.6.cli-migrations-v3
    ports:
    - "8082:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: "inherited_roles"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 15
      HASURA_GRAPHQL_MIGRATIONS_DIR: /data/hasura/migrations
      HASURA_GRAPHQL_METADATA_DIR: /data/hasura/metadata
      SAAS_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      HS_SUBSCRIPTION_BASE_URL: "http://hs-subscription:1340"
      HS_SAAS_BASE_URL: "http://hs-saas:1340"
    volumes:
    - ./hasura:/data/hasura
      
volumes:
  db_data:

