version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgrespassword}
  graphql-engine:
    image: hasura/graphql-engine:v2.0.6.cli-migrations-v3
    ports:
    - "8082:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-postgrespassword}@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: "inherited_roles"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET:-mysecrethasura}
      SAAS_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-postgrespassword}@postgres:5432/postgres
      HASURA_GRAPHQL_MIGRATIONS_DIR: /data/hasura/migrations
      HASURA_GRAPHQL_METADATA_DIR: /data/hasura/metadata
      MICRO_SUBSCRIPTIONS_BASE_URL: "http://hs-subscription:1340"
    volumes:
    - ./hasura:/data/hasura
      
volumes:
  db_data:

