name: Continuous Integration pipeline
on:
  push:
    branches:
      - main
      - feature/*
      - release/*
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'

env:
  HASURA_SAAS_VERSION: "v0.0.1-alpha.3"

  STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
  STRIPE_PRICE_ID: ${{ secrets.STRIPE_PRICE_ID }}
  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}

  HASURA_GRAPHQL_ADMIN_SECRET: mysecrethasura
  POSTGRES_PASSWORD: "postgrespassword"

jobs:
  test-saas:
    name: Test hasura data creation
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      - name: Starting up docker image
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Checking docker logs
        run: docker-compose logs
      
      - name: Downloading Hasura CLI
        run: curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
      
      - name: Executing tests
        run: ./scripts/hasura/test.sh

  create-artifacts:
    name: Creating artifacts
    needs: ["test-saas"]
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2

      - name: Migration Artifact
        uses: actions/upload-artifact@v2
        with:
          name: migrtations-latest
          path: |
            ./hasura/migrations

      - name: Metadata Artifact
        uses: actions/upload-artifact@v2
        with:
          name: metadata-latest
          path: |
            ./hasura/metadata